apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev  # Correctly aligned
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      # nodePort: 31005  # Optional: Use only if type is NodePort
  selector:
    app: backend  # Ensure this matches the labels in the Deployment
  type: LoadBalancer
