apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jeWJld3VvYWdnNW4udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: QWRtaW4xMjM=
